name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.1"
      
      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Install luacheck
        run: luarocks install luacheck
      
      - name: Run luacheck
        run: luacheck scripts/
